name: ood_fdrcps 
channels:
    - anaconda
    - conda-forge
    - pytorch
dependencies:
    - pip
    - python=3.9
    - numpy
    - numpy-base
    - matplotlib
    - matplotlib-base
    - scipy
    - pytorch
    - torchvision
    - pandas
    - pillow
    - seaborn
    - tqdm
    - detectron2
    - pyyaml
    - pycocotools
    - seaborn
    - statsmodels
    - joblib
